name: ikon-store-bot
region: fra

workers:
  # بوت التليجرام الموحد (Bot + Userbot)
  - name: ikon-bot
    github:
      repo: BASEL-DADA/telgram-bot-use-this-
      branch: main
      deploy_on_push: true
    build_command: pip install -r requirements.txt && python init_db.py
    run_command: python bot.py
    instance_count: 1
    instance_size_slug: apps-s-1vcpu-0.5gb
    source_dir: /
    envs:
      - key: DATABASE_URL
        scope: RUN_AND_BUILD_TIME
        type: SECRET
      - key: API_ID
        scope: RUN_TIME
        type: SECRET
      - key: API_HASH
        scope: RUN_TIME
        type: SECRET
      - key: SESSION_STRING
        scope: RUN_TIME
        type: SECRET
      - key: BOT_TOKEN
        scope: RUN_TIME
        type: SECRET
